# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.armafilter <- function(y, epsilon, x, initstate, mu, phi, theta, model) {
    .Call(`_tsarma_armafilter`, y, epsilon, x, initstate, mu, phi, theta, model)
}

.armafilter2 <- function(y, epsilon, x, mu, phi, theta, model) {
    .Call(`_tsarma_armafilter2`, y, epsilon, x, mu, phi, theta, model)
}

